include:
  - compose.yaml

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=mito
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./docker/volumes/oracle-data:/opt/oracle/oradata
    shm_size: 2g
    user: "54321:54321"
